lines = []
lines.append('<!DOCTYPE html>')
lines.append('<html lang="zh-CN">')
lines.append('<head>')
lines.append('<meta charset="UTF-8">')
lines.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
lines.append('<title>CMHK 决策仿真系统</title>')
lines.append('<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>')
lines.append('<link rel="stylesheet" href="style.css">')
lines.append('</head>')
lines.append('<body>')
lines.append('<aside class="sidebar">')
lines.append('  <div class="slogo">')
lines.append('    <div class="sl-row"><div class="sl-mark">CK</div><div><div class="sl-name">CMHK</div><div class="sl-sub">DECISION SIMULATION v2.0</div></div></div>')
lines.append('    <div class="sys-live"><div class="ldot"></div><span>实时数据同步中</span></div>')
lines.append('  </div>')
lines.append('  <nav class="nav">')
lines.append('    <div class="ngl">核心模块</div>')
lines.append('    <div class="ni act" onclick="goPage(this,0)"><span class="ni-d"></span>决策总览</div>')
lines.append('    <div class="ni" onclick="goPage(this,1)"><span class="ni-d"></span>财务分析</div>')
lines.append('    <div class="ni" onclick="goPage(this,2)"><span class="ni-d"></span>运营监控</div>')
lines.append('    <div class="ni" onclick="goPage(this,3)"><span class="ni-d"></span>市场洞察<span class="ni-b">3</span></div>')
lines.append('    <div class="ngl" style="margin-top:4px">智能决策</div>')
lines.append('    <div class="ni" onclick="goPage(this,4)"><span class="ni-d"></span>风险研判<span class="ni-b">2</span></div>')
lines.append('    <div class="ni" onclick="goPage(this,5)"><span class="ni-d"></span>场景模拟</div>')
lines.append('    <div class="ni" onclick="goPage(this,6)"><span class="ni-d"></span>行业趋势</div>')
lines.append('  </nav>')
lines.append('  <div class="sfooter">')
lines.append('    <button class="sync-btn" id="sync-btn" onclick="syncData()">同步数据</button>')
lines.append('    <div class="sf-time" id="sf-time">--:--:--</div>')
lines.append('  </div>')
lines.append('</aside>')
lines.append('<div class="main">')
lines.append('  <div class="topbar">')
lines.append('    <span class="tb-title" id="tb-title">决策总览</span>')
lines.append('    <span class="tb-sep">/</span>')
lines.append('    <span class="tb-sub" id="tb-sub">实时经营数据 · 内外部环境整合分析</span>')
lines.append('    <div class="tb-r"><span class="tb-time" id="tb-time">--:--:--</span><span class="bdg bdg-live">LIVE</span></div>')
lines.append('  </div>')
lines.append('  <div class="filter-bar">')
lines.append('    <span class="fb-label">时间范围</span>')
lines.append("    <button class=\"fb-btn\" onclick=\"setRange(this,'1M')\">近1月</button>")
lines.append("    <button class=\"fb-btn act\" onclick=\"setRange(this,'3M')\">近3月</button>")
lines.append("    <button class=\"fb-btn\" onclick=\"setRange(this,'6M')\">近6月</button>")
lines.append("    <button class=\"fb-btn\" onclick=\"setRange(this,'1Y')\">近1年</button>")
lines.append('    <span class="fb-sep"></span>')
lines.append("    <button class=\"fb-btn\" onclick=\"setRange(this,'YTD')\">YTD</button>")
lines.append('    <button class="fb-export" onclick="exportCSV()">导出 CSV</button>')
lines.append('  </div>')
lines.append('  <div class="content">')
print(f'Header: {len(lines)} lines')
with open('/Users/liaowang/Desktop/需求56/gen.py.part1', 'w') as f:
    f.write('\n'.join(lines))
